#server:
#  port: 8081
#  #context-path: /spring

#name: Aa
#age: 18
#在配置中写当前配置
#content: "name: ${name}, age: ${age}"

#自定义配置方法2
#person:
#  name: Bb
#  age: 20

#选择以何种配置文件启动项目
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/configtest
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#ddl-auto参数
#create：每次加载时都会删除上一次的生成的表，然后根据你的model类再重新来生成新表
#create-drop ：每次加载时根据model类生成表，但是一关闭,表就自动删除。
#update：第一次加载时根据model类会自动建立起表的结构（前提是先建立好数据库），
#        以后加载时根据 model类自动更新表结构
#validate ：每次加载时，验证创建数据库表结构，只会和数据库中的表进行比较，不会创建新表，但是会插入新值。